[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "doodle_sdk"
version = "0.1.0"
dynamic = ["description", "readme", "requires-python", "authors", "optional-dependencies", "classifiers", "dependencies"]

